# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2
---
spec:
  inputs:
    dockerfile_dir:
      default: $CI_PROJECT_DIR
    harbor_push_project:
      description: The GitLab project path for the push-and-sign pipeline.
      type: string
      default: opentalk/opentalk-devops/push-and-sign-images-for-the-opentalk-namespace
    harbor_namespace_suffix:
      description: >
        Suffix appended to the Harbor namespace, typically the service name
        (e.g. `controller`).
      type: string
    additional_labels:
      description: Additional labels for container scanning, usually the team label.
      type: string
      default: ''
    trivy_ignore_prefix:
      description: Prefix for the .trivyignore file per flavor.
      type: string
      default: .trivyignore-

---

package:container-build-mr:
  parallel:
    matrix:
      - FLAVOR: !reference [.template_vars, FLAVORS]
  stage: package
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      allow_failure: true
  image:
    name: quay.io/buildah/stable:v1.43.0
    pull_policy: if-not-present
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - >
      if [[ $FLAVOR == "" ]]; then
        DOCKERFILE="Dockerfile"
        TAG="$CI_COMMIT_REF_SLUG"
      else
        DOCKERFILE="Dockerfile-$FLAVOR"
        TAG="$CI_COMMIT_REF_SLUG-$FLAVOR"
      fi
    - buildah build -f $[[ inputs.dockerfile_dir ]]/$DOCKERFILE -t "$CI_REGISTRY_IMAGE:$TAG"
    - buildah push "$CI_REGISTRY_IMAGE:$TAG"

package:container-build:
  parallel:
    matrix:
      - FLAVOR: !reference [.template_vars, FLAVORS]
  stage: package
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^release\/v\d+\.\d+\.x$/
  image:
    name: quay.io/buildah/stable:v1.43.0
    pull_policy: if-not-present
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - IMAGE_TAG=$FLAVOR-$CI_COMMIT_SHORT_SHA
    - buildah build -f $[[ inputs.dockerfile_dir ]]/Dockerfile-$FLAVOR -t $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - buildah push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"

package:read-tags:
  stage: package
  needs: []
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
  image:
    name: alpine/git:v2.52.0
    entrypoint: ['']
    pull_policy: if-not-present
  artifacts:
    reports:
      dotenv: package.env
  script:
    - git fetch --tags
    - |
      TAGS=$(git tag --list \
              | grep "^v[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+$" \
              | sort -V \
              | head -n -1 \
              | tr '\n' ' ')
    - echo "TAGS=$TAGS" > package.env

package:container-create-and-push-tags:
  parallel:
    matrix:
      - FLAVOR: !reference [.template_vars, FLAVORS]
  stage: package
  needs:
    - job: package:read-tags
      optional: true
    - job: package:container-build
  rules:
    # Prevent forks from triggering the downstream pipeline
    - if: $CI_PROJECT_ROOT_NAMESPACE != "opentalk"
      when: never
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^release\/v\d+\.\d+\.x$/
  image:
    name: git.opentalk.dev:5050/opentalk/ci/templates/rust-container-build:v2
    entrypoint: ['']
    pull_policy: if-not-present
  variables:
    DEFAULT_FLAVOR: !reference [.template_vars, DEFAULT_FLAVOR]
  script:
    - >
      TAGS_TO_PUSH=$(create-container-tags
      "${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME}"
      "$TAGS" "$FLAVOR" "$DEFAULT_FLAVOR" "$CI_DEFAULT_BRANCH")
    - |
      for tag in $TAGS_TO_PUSH; do
        skopeo copy \
        --src-creds="${CI_REGISTRY_USER}":"${CI_REGISTRY_PASSWORD}" \
        --dest-creds="${CI_REGISTRY_USER}":"${CI_REGISTRY_PASSWORD}" \
        "docker://${CI_REGISTRY_IMAGE}:$FLAVOR-${CI_COMMIT_SHA:0:8}" "docker://${CI_REGISTRY_IMAGE}:$tag"
      done
    - echo "TAGS_$FLAVOR=$TAGS_TO_PUSH" > package.env
  artifacts:
    reports:
      dotenv: package.env

push-and-sign-images-to-harbor:
  parallel:
    matrix:
      - FLAVOR: !reference [.template_vars, FLAVORS]
  needs:
    - job: package:container-create-and-push-tags
      parallel:
        matrix:
          - FLAVOR: !reference [.template_vars, FLAVORS]
  rules:
    # Prevent forks from triggering the downstream pipeline
    - if: $CI_PROJECT_ROOT_NAMESPACE != "opentalk"
      when: never
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^release\/v\d+\.\d+\.x$/
  stage: package
  variables:
    PIPELINE_FULL_IMAGE_NAME: $CI_REGISTRY_IMAGE
    PIPELINE_NAMESPACE_SUFFIX: $[[ inputs.harbor_namespace_suffix ]]
    PIPELINE_TAGS_ENV_NAME: TAGS_$FLAVOR
  trigger:
    project: $[[ inputs.harbor_push_project ]]
    strategy: depend
    forward:
      pipeline_variables: true

read-trivy-ignore-file:
  parallel:
    matrix:
      - FLAVOR: !reference [.template_vars, FLAVORS]
  stage: package
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  script:
    - echo "TRIVY_IGNORE_STR_$FLAVOR=$(
      cat $CI_PROJECT_DIR/$[[ inputs.trivy_ignore_prefix ]]$FLAVOR | sed -n 'H;${x;s/^\n//;s/\n/\\n/g;p}'
      )" > package.env
  artifacts:
    reports:
      dotenv: package.env
